### ISSUE TITLE
What's the correct sequence of dict2dzn

### ISSUE THREAD

**Issue by shuaiwang88** [paolodragone/pymzn#42]
Why the output sequence does not match the original input? 
```
import pymzn

a_string = {'e1', 'e2', 'e3', 'e4'}

pymzn.dict2dzn({'out':a_string}, fout="test.dzn")

##out = {e2, e4, e3, e1};
```
I am not sure the index of the paramter is valid or not.

**Comment by paolodragone** [comment]
Hi @shuaiwang88 
That's because `{'e1', 'e2', 'e3', 'e4'}` is a set (both in Python and MiniZinc). Sets are unordered data structures so the order of iteration is not guaranteed.
If you need the to keep the order you need to use Python lists, which are converted into minizinc arrays.
Does this help?

**Comment by shuaiwang88** [comment]
@paolodragone  I am looping over the a_string as index domain to simulate a parameter in array. This could effect the sequence of the parameter since the set is not order while the array is ordered. 

I will try the list form. Thanks!
